export const ADD_POKEMON_ACTION = 'ADD_POKEMON_ACTION';
export const REMOVE_POKEMON_ACTION = 'REMOVE_POKEMON_ACTION';
export const SELECT_POKEMON_ACTION = 'SELECT_POKEMON_ACTION';
export const DISELECT_POKEMON_ACTION = 'DISELECT_POKEMON_ACTION';